url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Moses blog" # the name of your site, e.g. ACME Corp.


twitter_username: mosesturnervevo
github_username: slitcch
instagram_username: mosesturnervevo

content:
  ordered_header_pages: 
    - index.markdown
    - blog.markdown

